# ChunkDiscovery プラグイン設定ファイル

# データベース設定（MySQL専用）
db:
  host: "localhost"
  port: 3306
  name: "minecraft_chunks"
  user: "minecraft_user"
  pass: "your_password"

# ワールドボーダー設定
border:
  # デフォルト設定（未設定のワールド用）
  initial_size: 100.0  # 初期ボーダーサイズ
  expansion_per_chunk: 2.0  # チャンク発見1つあたりの拡張量

  # ワールドタイプ別設定（環境タイプで指定）
  world_types:
    overworld:  # オーバーワールド環境（Environment.NORMAL）
      initial_size: 16.0
      expansion_per_chunk: 4.0
    nether:     # ネザー環境（Environment.NETHER）
      initial_size: 32.0
      expansion_per_chunk: 16
    end:        # エンド環境（Environment.THE_END）
      initial_size: 60000.0
      expansion_per_chunk: 2.0

# 報酬設定（全ワールド共通）
rewards:
  # 世界初発見報酬
  world_first:
    item:
      material: DIAMOND
      amount: 3
    experience: 100
    effects:
      - type: SPEED
        duration: 1200  # 60秒
        amplifier: 1

  # 個人初発見報酬
  personal_first:
    item:
      material: EMERALD
      amount: 5
    experience: 10
    effects:
      - type: REGENERATION
        duration: 600  # 30秒
        amplifier: 0

  # マイルストーン報酬（全体の発見数に基づく）
  milestones:
    10:  # 10チャンク発見（全ワールド合計）
      item:
        material: IRON_INGOT
        amount: 5
      experience: 50
    25:  # 25チャンク発見
      item:
        material: GOLD_INGOT
        amount: 3
      experience: 100
      effects:
        - type: LUCK
          duration: 3600  # 3分
          amplifier: 1
    50:  # 50チャンク発見
      item:
        material: DIAMOND
        amount: 2
      experience: 200
      effects:
        - type: SPEED
          duration: 2400  # 2分
          amplifier: 1
        - type: JUMP_BOOST
          duration: 2400
          amplifier: 1
    100:  # 100チャンク発見
      item:
        material: NETHERITE_INGOT
        amount: 1
      experience: 500
      effects:
        - type: HERO_OF_THE_VILLAGE
          duration: 6000  # 5分
          amplifier: 2
    1000:  # 100チャンク発見
      item:
        material: END_PORTAL_FRAME
        amount: 12
      experience: 5000
      effects:
        - type: HERO_OF_THE_VILLAGE
          duration: 6000  # 5分
          amplifier: 5